sudo: false
language: php

addons:
  mariadb: '10.0'
  hosts:
    - tenant.testing
    - local.testing

env:
  - DB=mysql TENANCY_SYSTEM_CONNECTION_NAME=mysql LIMIT_UUID_LENGTH_32=1 DB_USERNAME=root
  - DB=mariadb TENANCY_SYSTEM_CONNECTION_NAME=mysql DB_USERNAME=root
  - DB=pgsql TENANCY_SYSTEM_CONNECTION_NAME=pgsql DB_USERNAME=postgres
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
matrix:
    include:
      - webserver: apache
        env: WEBSERVER=apache
      - webserver: nginx
        env: WEBSERVER=nginx

jobs:
    allow_failures:
      - php: nightly
before_install:
  - travis_retry composer self-update
install:
  - composer update --prefer-dist --no-interaction -o
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS testing;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE testing;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mariadb' ] || [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'; fi"
script:
  - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml -vv

cache:
  directories:
    - $HOME/.composer/cache
